---
dependencies: []
galaxy_info:
  description: Elastic auditbeat for information security
  min_ansible_version: 2.10
  platforms:
  - name: Debian
    versions: [all]
  - name: Ubuntu
    versions: [all]
