---
- name: test message
  debug:
    msg: "it works!"

- name: Disable debug-shell SystemD Service
  ansible.builtin.systemd:
    name: debug-shell
    enabled: no

- name: Disable Ctrl-Alt-Del Reboot Activation
  ansible.builtin.file:
    src: /dev/null
    dest: /etc/systemd/system/ctrl-alt-del.target
    state: link

- name: ensure necessary configuration lines
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line}}"
    create: yes
  with_items:
  - path: /etc/systemd/system.conf
    line: CtrlAltDelBurstAction=none
  - path: /etc/login.defs
    line: CREATE_HOME yes

- name: Set Password Hashing Algorithm
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    line: ENCRYPT_METHOD SHA512
    create: yes

- name: Set Password Hashing Algorithm in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    line: ENCRYPT_METHOD SHA512
    create: yes

- name: get non-unique users list
  shell: "getent passwd | awk -F: '{ print $1}' | uniq -d"
  register: result

- debug: var=result.stdout
  when: result.stdout != ""


- name: 7. Set Account Expiration Following Inactivity
  copy:
    dest: /etc/default/useradd
    src: usersadd

- name: 9. Verify All Account Password Hashes are Shadowed
  shell: |
    awk -F: '$2!="x"' /etc/passwd
  register: passwd
  changed_when: passwd.stdout != ""

- debug: var=passwd.stdout
  when: passwd.stdout != ""

- name: 12.Verify /boot/grub2/grub.cfg Permissions
  copy:
    dest: /etc/motd
    content: "{{motd}}"

- name: 13.Verify /boot/grub2/grub.cfg Permissions
  #использовать такую конструкцию для изменения прав доступа
  file:
    dest: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: 0600 #важно поставить 0 перед 600

